/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Week9_JNIDemo */

#ifndef _Included_Week9_JNIDemo
#define _Included_Week9_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
#undef Week9_JNIDemo_FOCUS_TRAVERSABLE_UNKNOWN
#define Week9_JNIDemo_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Week9_JNIDemo_FOCUS_TRAVERSABLE_DEFAULT
#define Week9_JNIDemo_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Week9_JNIDemo_FOCUS_TRAVERSABLE_SET
#define Week9_JNIDemo_FOCUS_TRAVERSABLE_SET 2L
#undef Week9_JNIDemo_TOP_ALIGNMENT
#define Week9_JNIDemo_TOP_ALIGNMENT 0.0f
#undef Week9_JNIDemo_CENTER_ALIGNMENT
#define Week9_JNIDemo_CENTER_ALIGNMENT 0.5f
#undef Week9_JNIDemo_BOTTOM_ALIGNMENT
#define Week9_JNIDemo_BOTTOM_ALIGNMENT 1.0f
#undef Week9_JNIDemo_LEFT_ALIGNMENT
#define Week9_JNIDemo_LEFT_ALIGNMENT 0.0f
#undef Week9_JNIDemo_RIGHT_ALIGNMENT
#define Week9_JNIDemo_RIGHT_ALIGNMENT 1.0f
#undef Week9_JNIDemo_serialVersionUID
#define Week9_JNIDemo_serialVersionUID -7644114512714619750LL
#undef Week9_JNIDemo_serialVersionUID
#define Week9_JNIDemo_serialVersionUID 4613797578919906343LL
#undef Week9_JNIDemo_INCLUDE_SELF
#define Week9_JNIDemo_INCLUDE_SELF 1L
#undef Week9_JNIDemo_SEARCH_HEAVYWEIGHTS
#define Week9_JNIDemo_SEARCH_HEAVYWEIGHTS 1L
#undef Week9_JNIDemo_OPENED
#define Week9_JNIDemo_OPENED 1L
#undef Week9_JNIDemo_serialVersionUID
#define Week9_JNIDemo_serialVersionUID 4497834738069338734LL
#undef Week9_JNIDemo_DEFAULT_CURSOR
#define Week9_JNIDemo_DEFAULT_CURSOR 0L
#undef Week9_JNIDemo_CROSSHAIR_CURSOR
#define Week9_JNIDemo_CROSSHAIR_CURSOR 1L
#undef Week9_JNIDemo_TEXT_CURSOR
#define Week9_JNIDemo_TEXT_CURSOR 2L
#undef Week9_JNIDemo_WAIT_CURSOR
#define Week9_JNIDemo_WAIT_CURSOR 3L
#undef Week9_JNIDemo_SW_RESIZE_CURSOR
#define Week9_JNIDemo_SW_RESIZE_CURSOR 4L
#undef Week9_JNIDemo_SE_RESIZE_CURSOR
#define Week9_JNIDemo_SE_RESIZE_CURSOR 5L
#undef Week9_JNIDemo_NW_RESIZE_CURSOR
#define Week9_JNIDemo_NW_RESIZE_CURSOR 6L
#undef Week9_JNIDemo_NE_RESIZE_CURSOR
#define Week9_JNIDemo_NE_RESIZE_CURSOR 7L
#undef Week9_JNIDemo_N_RESIZE_CURSOR
#define Week9_JNIDemo_N_RESIZE_CURSOR 8L
#undef Week9_JNIDemo_S_RESIZE_CURSOR
#define Week9_JNIDemo_S_RESIZE_CURSOR 9L
#undef Week9_JNIDemo_W_RESIZE_CURSOR
#define Week9_JNIDemo_W_RESIZE_CURSOR 10L
#undef Week9_JNIDemo_E_RESIZE_CURSOR
#define Week9_JNIDemo_E_RESIZE_CURSOR 11L
#undef Week9_JNIDemo_HAND_CURSOR
#define Week9_JNIDemo_HAND_CURSOR 12L
#undef Week9_JNIDemo_MOVE_CURSOR
#define Week9_JNIDemo_MOVE_CURSOR 13L
#undef Week9_JNIDemo_NORMAL
#define Week9_JNIDemo_NORMAL 0L
#undef Week9_JNIDemo_ICONIFIED
#define Week9_JNIDemo_ICONIFIED 1L
#undef Week9_JNIDemo_MAXIMIZED_HORIZ
#define Week9_JNIDemo_MAXIMIZED_HORIZ 2L
#undef Week9_JNIDemo_MAXIMIZED_VERT
#define Week9_JNIDemo_MAXIMIZED_VERT 4L
#undef Week9_JNIDemo_MAXIMIZED_BOTH
#define Week9_JNIDemo_MAXIMIZED_BOTH 6L
#undef Week9_JNIDemo_serialVersionUID
#define Week9_JNIDemo_serialVersionUID 2673458971256075116LL
#undef Week9_JNIDemo_RAND_BOUNDS
#define Week9_JNIDemo_RAND_BOUNDS 100L
#undef Week9_JNIDemo_WIN_WIDTH
#define Week9_JNIDemo_WIN_WIDTH 900L
#undef Week9_JNIDemo_WIN_HEIGHT
#define Week9_JNIDemo_WIN_HEIGHT 500L
/*
 * Class:     Week9_JNIDemo
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Week9_JNIDemo_calculateMean
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     Week9_JNIDemo
 * Method:    calculateSTDDev
 * Signature: ([ID)D
 */
JNIEXPORT jdouble JNICALL Java_Week9_JNIDemo_calculateSTDDev
  (JNIEnv *, jobject, jintArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
