/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Week8_JNIDemo */

#ifndef _Included_Week8_JNIDemo
#define _Included_Week8_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Week8_JNIDemo
 * Method:    calculateSTDDev
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Week8_JNIDemo_calculateSTDDev(JNIEnv *, jobject, jintArray, jdouble);

/*
 * Class:     Week8_JNIDemo
 * Method:    calculateMean
 * Signature: ([I)D
 */
JNIEXPORT jdouble JNICALL Java_Week8_JNIDemo_calculateMean(JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
